# Вправи
(використовувати тільки матричні операції)

1. Отримати суму елементів та суму квадратів елементів вектора:

In [88]:
import numpy as np
import linalg
v = np.array([1, 2, 3, 4, 5, 6])
print(np.ones(len(v)).dot(v))
print (v*v)
print(np.ones(len(v)).dot(v*v))
#np.linalg.matrix_power(v,2)

print(len(v.shape))


21.0
[ 1  4  9 16 25 36]
91.0
1


In [16]:
# np.sum(v) не можна використовувати

In [17]:
v.dot(v)

91

2. Для вектора попереднього завдання побудувати вектор, кожним елементом якого є середнє значення вектора.

In [55]:
np.ones(len(v))* np.average(v, weights =np.ones(len(v)))

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

3. Написати функцію, яка приймає на вхід довільну кількість матриць, перевіряє, чи можна їх перемножити, і якщо можна, то повертає розмірність результату (можна скористатися циклом). 

In [108]:
def matrix_mult(args_1, args_2):
    if len(args_1.shape)>1:
        print(args_1.shape)
        if args_1.shape[1]==args_2.shape[0]:
            return np.array([args_2.shape[0], args_1.shape[1]])
        else:
            return False
    else:
        return False

  

4.Обчислити вираз:

$$\sum_{i=1}^n(x_{i} - avg(x))^{2}$$

In [92]:
 
avr_v=np.average(v, weights =np.ones(len(v)))
#print(avr_v)
Xi_avr_v=(v-np.ones(len(v))*avr_v)
print(np.ones(len(v)).dot(Xi_avr_v*Xi_avr_v))
 

17.5


5. Вивести матрицю, яка при множенні на вектор зліва (Мх) приводить його до форми відхилення від середнього значення. Тобто, кожним елементом вектора-результату буде відповідний елемент вхідного вектора мінус середнє значення. Матриця М не повинна залежати від вхідного вектора x, а лише від його довжини. Іншими словами, для створення такої матриці має бути достатньо лише знання скільки в них елементів.

6. Розв'язати систему рівнянь (можна скористатися функцією кореня):

$$
47a^{2} + 71b - 2c = 3\\\
11b - 8c = 3\\\
a^{2} + b + c = 24\\\
$$

In [93]:
a=np.array([[47,71,-2],[0,11,-8],[1,1,1]])
print(a)
b=np.array([3,3,24])
print(b)
np.linalg.solve(a, b)



[[47 71 -2]
 [ 0 11 -8]
 [ 1  1  1]]
[ 3  3 24]
None


In [109]:
matrix_mult(a, b)

(3, 3)


array([3, 3])