# Модуль numpy

# Вправи

In [5]:

import numpy as np

1. Дано: одновимірний масив

In [6]:
arr = np.random.rand(1000)

Завдання: замінити всі елементи цього масиву, які більші за середнє цього масива на це середнє значення.

In [7]:
arr = np.random.rand(1000)
#avr_arr=sum(arr)/len(arr)
avr_arr=np.sum(arr)/np.shape(arr)
print (avr_arr)
for i, val in enumerate(arr):
    if val>avr_arr:
        arr[i]=avr_arr
print (arr)
    

[0.49566681]
[0.29567581 0.49566681 0.49566681 0.49566681 0.30634258 0.06277024
 0.49566681 0.06620604 0.10157344 0.49566681 0.49566681 0.45968165
 0.36014296 0.49566681 0.09506839 0.48131047 0.49566681 0.49566681
 0.49566681 0.42376266 0.49566681 0.49566681 0.07505303 0.49566681
 0.49566681 0.06935212 0.16740636 0.49566681 0.30412227 0.40109346
 0.49566681 0.49566681 0.49566681 0.07553701 0.46925123 0.45194223
 0.49566681 0.18686532 0.49566681 0.49566681 0.33895837 0.49566681
 0.26220984 0.49566681 0.49566681 0.41532374 0.0423326  0.49566681
 0.49566681 0.25063422 0.49566681 0.02872687 0.49566681 0.49282719
 0.49566681 0.49566681 0.41854168 0.49566681 0.08317681 0.49566681
 0.44354846 0.43900818 0.39211762 0.45418127 0.06645807 0.49566681
 0.49566681 0.49566681 0.07804805 0.33047177 0.49566681 0.42316238
 0.49566681 0.49566681 0.49566681 0.49566681 0.24544293 0.0148072
 0.2737462  0.49566681 0.49566681 0.49566681 0.439838   0.22872976
 0.49566681 0.49566681 0.49566681 0.24195108 0.475

2. Для масиву з попередньої задачі імплементувати сигмоїдну функцію:

$$y = \frac{1} {1 + e^{-x}}$$

In [14]:
arr = np.random.rand(1000)
arr=1/(1+np.power(np.exp(1),arr))
'''
avr_arr=np.sum(arr)/np.shape(arr)
print (avr_arr)
for i, val in enumerate(arr):
    if val>avr_arr:
        arr[i]=avr_arr
print (arr)
'''

'\navr_arr=np.sum(arr)/np.shape(arr)\nprint (avr_arr)\nfor i, val in enumerate(arr):\n    if val>avr_arr:\n        arr[i]=avr_arr\nprint (arr)\n'

3. Вирішити завдання про таблицю співробітників використовуючи numpy (вивести на екран інформацію про співробітників, прийнятих на роботу після 2012 року та з ЗП понад 2000; надрукувати можна без форматування)

workers_table = np.array([
    [1, 'B', 1000, 2013],
    [2, 'B', 1500, 2014],
    [3, 'B', 1800, 2012],
    [4, 'A', 2500, 2016],
    [5, 'A', 3500, 2017],
    [6, 'A', 4500, 2011],
], dtype=object)


In [15]:
workers_table = np.array([
    [1, 'B', 1000, 2013],
    [2, 'B', 1500, 2014],
    [3, 'B', 1800, 2012],
    [4, 'A', 2500, 2016],
    [5, 'A', 3500, 2017],
    [6, 'A', 4500, 2011],
], dtype=object)
#print(workers_table[:,3])
#year_f= np.where(workers_table[:,3]>2012,workers_table[:,0],'')
year_f= np.asarray(workers_table[:,3]>2012).nonzero()
salary_f= np.asarray(workers_table[:,2]>2000).nonzero()
print(f'прийнятих на роботу після 2012 року {workers_table[year_f]}')
print(f' з ЗП понад 2000 {workers_table[salary_f]}')


прийнятих на роботу після 2012 року [[1 'B' 1000 2013]
 [2 'B' 1500 2014]
 [4 'A' 2500 2016]
 [5 'A' 3500 2017]]
 з ЗП понад 2000 [[4 'A' 2500 2016]
 [5 'A' 3500 2017]
 [6 'A' 4500 2011]]


4. У таблиці співробітників з попередньої задачі, додати ще один стовпець, де записати різницю між ЗП співробітника та середньою ЗП усіх співробітників.

In [122]:
workers_table = np.array([
    [1, 'B', 1000, 2013],
    [2, 'B', 1500, 2014],
    [3, 'B', 1800, 2012],
    [4, 'A', 2500, 2016],
    [5, 'A', 3500, 2017],
    [6, 'A', 4500, 2011],
], dtype=object)
avr_salary=np.sum(workers_table[:,2])/len(workers_table[:,2])
workers_table=np.append(workers_table.transpose(),workers_table[:,2]-avr_salary)
print (workers_table.reshape(-1,6).transpose())

[[1 'B' 1000 2013 -1466.6666666666665]
 [2 'B' 1500 2014 -966.6666666666665]
 [3 'B' 1800 2012 -666.6666666666665]
 [4 'A' 2500 2016 33.333333333333485]
 [5 'A' 3500 2017 1033.3333333333335]
 [6 'A' 4500 2011 2033.3333333333335]]


5. У таблиці співробітників знайти та вивести на екран мінімальний рік прийому на роботу в кожному департаменті.

In [127]:
#import pandas as pd

workers_table = np.array([
    [1, 'B', 1000, 2013],
    [2, 'B', 1500, 2014],
    [3, 'B', 1800, 2012],
    [4, 'A', 2500, 2016],
    [5, 'A', 3500, 2017],
    [6, 'A', 4500, 2011],
], dtype=object)

for i in np.unique(workers_table[:,1]):
    print(f'{i} - {workers_table[np.asarray(workers_table[:,1]==i).nonzero()][:,3].min()}')
 



A - 2011
B - 2012


6. Дана таблиця A

In [7]:
A = np.array([
    [2, 5, 8, 56],
    [4, 9, 1, 23],
    [6, 12, 84, 55]
])

Завдання: нормалізувати колонки (зробити так, щоб довжина векторів у колонках була 1)

In [173]:
 
A = np.array([
    [2, 5, 8, 56],
    [4, 9, 1, 23],
    [6, 12, 84, 55]
])

for i in np.arange(0,np.shape(A)[1]):
    print(A[:,i]/np.sum(A[:,i]))

[0.16666667 0.33333333 0.5       ]
[0.19230769 0.34615385 0.46153846]
[0.08602151 0.01075269 0.90322581]
[0.41791045 0.17164179 0.41044776]
